spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.2.40:5432/music_service?serverTimezone=UTC
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://192.168.2.40:5432/music_service?serverTimezone=UTC
    user: postgres
    password: postgres
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: password